### ISSUE TITLE
If TLSEnable is false, ssl_context is not initialized

### ISSUE THREAD

**Issue by bjerickson** [aerospike/aerospike-collectd#7]
```
[2017-02-02 11:41:57] Unhandled python exception in read callback: UnboundLocalError: local variable 'ssl_context' referenced before assignment
[2017-02-02 11:41:57] Traceback (most recent call last):
[2017-02-02 11:41:57]   File "/opt/collectd-aerospike/aerospike_plugin.py", line 755, in read
    capath=ca_path, protocols=protocols, cert_blacklist=blacklist, crl_check=crl_check, crl_check_all=crl_check_all, tls_name=tls_name)
[2017-02-02 11:41:57]   File "/opt/collectd-aerospike/aerospike_plugin.py", line 230, in connect
```

**Comment by bjerickson** [comment]
TLSEnable in collectd, tls_enable in the python code

**Comment by rguo-aerospike** [comment]
Don't see the issue:

aerospike_plugin.py: line 660
`elif node.key == 'TLSEnable':
                self.tls_enable = node.values[0]`
